name: RWIS + RTMA Snapshot Logger (Windows)

on:
  schedule:
    - cron: '3,33 * * * *'  # Twice hourly at :03 and :33 UTC
  workflow_dispatch:        # Manual trigger

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    env:
      COTRIP_API_KEY: ${{ secrets.COTRIP_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy pandas xarray requests scipy cfgrib

      - name: Run RWIS/RTMA snapshot script
        run: python rwis_rtma_logger.py

      - name: Commit and push updated NetCDF
        shell: pwsh
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          $filename = "rwis_rtma_$((Get-Date).ToUniversalTime().ToString('yyyyMMdd')).nc"
          if (Test-Path $filename) {
            git add $filename
            if (git diff --cached --quiet) {
              Write-Output "No changes to commit in $filename"
            } else {
              git pull origin main --rebase

              git commit -m "Update NetCDF snapshot for $((Get-Date).ToUniversalTime().ToString('yyyy-MM-dd'))"

              git push origin main
            }
          } else {
            Write-Output "No NetCDF file found to commit."
          }
