name: RWIS + RTMA Snapshot Logger (Windows)

on:
  schedule:
    - cron: '3,33 * * * *'  # Twice hourly at :03 and :33 UTC
  workflow_dispatch:        # Manual trigger

permissions:
  contents: write  # Required to allow pushing changes

jobs:
  build:
    runs-on: windows-latest

    env:
      COTRIP_API_KEY: ${{ secrets.COTRIP_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # Needed for pull/rebase

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy pandas xarray requests scipy cfgrib

      - name: Run RWIS/RTMA snapshot script
        run: python rwis_rtma_logger.py

      - name: Commit and push updated NetCDF
        shell: pwsh
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Compute filename dynamically
          $filename = "rwis_rtma_$((Get-Date).ToUniversalTime().ToString('yyyyMMdd')).nc"

          if (Test-Path $filename) {
            git add $filename

            # Only continue if there are changes
            if (git diff --cached --quiet) {
              Write-Output "No changes to commit in $filename"
              exit 0
            }

            # Pull and rebase before pushing to avoid conflicts
            git pull origin main --rebase

            git commit -m "Update NetCDF snapshot for $((Get-Date).ToUniversalTime().ToString('yyyy-MM-dd HH:mm')) UTC"

            git push origin HEAD:main
          } else {
            Write-Output "No NetCDF file found to commit."
          }
